[pyprland]
plugins = ["scratchpads"]

[scratchpads.BW]
animation = "fromRight"
position = "55% 5%"
command = "bitwarden-desktop"
class = "Bitwarden"
size = "40% 45%"
unfocus = "hide"

[scratchpads.calc]
animation = "fromRight"
command = "galculator"
class = "galculator" 
size = "25% 40%"
unfocus = "hide"

[scratchpads.mc]
animation = "fromTop"
position = "29% 4%"
command = "morgen"
class = "morgen"
size = "40% 45%"
unfocus = "hide" 

[scratchpads.nfm]
animation = "fromTop"
position = "5% 4%"
command = "nemo"
class = "nemo"
size = "40% 45%"
unfocus = "hide" 

[scratchpads.quickiesticky]
animation = "fromBottom"
position = "5% 55%"
command = "gedit  '/mnt/ntfs/Obsidian-Lgn-win/05. Quickies/1. Quick Notes-LGN.md'"
class = "gedit"
size = "30% 40%"
unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
position = "65% 5%"
command = "pavucontrol"
class = "pavucontrol"
size = "30% 50%"
unfocus = "hide" 